env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2021
  sourceType: module
plugins:
  - prettier
settings:
  react:
    version: detect
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  quotes:
    - error
    - single
    - avoidEscape: true
  no-prototype-builtins: 'off'
  no-sequences:
    - error
  prettier/prettier:
    - error
  semi:
    - error
    - always
